# **************************************************************************
# *
# * Authors:   Blanca Pueche (blanca.pueche@cnb.csis.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import json
import string
import re

import os, glob
import pyworkflow.protocol.params as params
from pwem.protocols import EMProtocol
from pyworkflow.object import String, Float
import shutil

from pwchem import Plugin
from pwchem.constants import RDKIT_DIC
from pwem.convert import cifToPdb
from flowrroot.constants import FLOWR_DIC

from pwem.objects import  AtomStruct, SetOfAtomStructs
from pwem.objects import Sequence, SetOfSequences
from pwchem.objects import SmallMolecule, SetOfSmallMolecules
from pwchem.protocols.Sequences.protocol_define_sequences import ProtDefineSetOfSequences
from pwchem.utils.utilsFasta import parseFasta
from .protocol_denovo import ProtDenovoGeneration

from .. import utils

class ProtInpainting(EMProtocol):
    """
    AI Generated:

    Molecular Inpainting Protocol

    This protocol performs structure-guided molecular inpainting using the
    FLOWR generative framework. Starting from a protein–ligand complex, the
    user specifies one or more atoms within the ligand that should be modified.
    The selected region is then redesigned while the remaining molecular
    structure is preserved.

    Molecular inpainting is analogous to image inpainting: instead of generating
    an entirely new molecule, the model reconstructs or replaces only specific
    parts of an existing ligand while maintaining compatibility with the
    protein binding pocket.

    This approach is particularly useful for lead optimization, scaffold
    refinement, and targeted modification of molecular regions suspected to
    affect potency, selectivity, toxicity, or physicochemical properties.

    Core Concepts
    -------------
    Structure-Based Ligand Optimization:
        Molecular modifications are guided by the three-dimensional structure
        of the protein binding site.

    Substructure Inpainting:
        Selected atoms of the reference ligand are removed and regenerated by
        the model while preserving the remainder of the molecule.

    FLOWR Model:
        A diffusion-based molecular generation framework capable of generating
        chemically valid structures conditioned on protein and ligand context.

    Local Molecular Redesign:
        Unlike de novo generation, only specific molecular regions are modified,
        enabling controlled exploration around existing lead compounds.

    Affinity Prediction:
        Generated molecules may optionally be evaluated using FLOWR affinity
        prediction models.

    Workflow
    --------
    1. Input preparation:
        - A protein structure is provided.
        - A reference ligand is selected.

    2. Structure preprocessing:
        - Protein and ligand files are converted into FLOWR-compatible formats.
        - Pocket information is extracted from the protein structure.

    3. Region selection:
        - The user specifies atom indices corresponding to the region to be
          redesigned.
        - These atoms define the inpainting target.

    4. Molecular inpainting:
        - FLOWR reconstructs the selected molecular region.
        - The remaining ligand structure is preserved.
        - New atoms and bonds are generated while maintaining compatibility
          with the protein pocket.

    5. Optional optimization:
        - Generated molecules may be chemically optimized.

    6. Optional affinity prediction:
        - Binding affinity estimates are calculated for generated ligands.

    7. Output generation:
        - Generated molecules are exported as individual SDF files.
        - Results are stored in a SetOfSmallMolecules object.

    Input
    -----
    - inputAtomStruct:
        Protein structure containing the target binding site.

    - inputSetOfMols:
        SetOfSmallMolecules containing reference ligands.

    - referenceMol:
        Name of the ligand to be modified.

    Parameters
    ----------
    Region Selection
    ~~~~~~~~~~~~~~~~
    - atoms:
        Atom indices defining the region to be modified.

        Accepted formats:
            - Individual atoms:
                13,14,15

            - Atom ranges:
                13-18

            - Combined notation:
                1-3,7,10-12

        The selected atoms are regenerated during the inpainting process,
        while the rest of the molecule remains fixed.

    Pocket Definition
    ~~~~~~~~~~~~~~~~~
    - pocketCutoff:
        Distance cutoff (Å) used to define pocket residues surrounding the
        reference ligand.

    - cutPocket:
        If enabled, only the binding pocket is provided to the model.
        Otherwise, the complete protein structure is used.

    Generation Control
    ~~~~~~~~~~~~~~~~~~
    - nMolecules:
        Number of molecules to generate.

    - seed:
        Random seed for reproducible generation.

    - sampleIters:
        Maximum number of sampling iterations.

    - noiseScale:
        Amount of stochastic noise introduced during generation.
        Higher values generally increase structural diversity.

    - sampleMolSizes:
        Enables stochastic sampling of molecular sizes.

    - batchCost:
        Internal generation batch-size parameter used by FLOWR.

    Pocket Constraints
    ~~~~~~~~~~~~~~~~~~
    - minPocketSize:
        Minimum number of atoms required in the extracted pocket.

    - maxPocketSize:
        Maximum number of atoms allowed in the extracted pocket.

    Substructure Constraints
    ~~~~~~~~~~~~~~~~~~~~~~~~
    - filterCondSubstructure:
        Applies strict filtering to ensure generated molecules preserve the
        required molecular substructure. Molecules that fail the constraint
        are discarded.

    Ligand Postprocessing
    ~~~~~~~~~~~~~~~~~~~~~
    - optimizeLigands:
        Perform chemical optimization after generation.

    - kekulize:
        Apply kekulization during molecular processing.

    Affinity Evaluation
    ~~~~~~~~~~~~~~~~~~~
    - affinity:
        Predict protein–ligand binding affinity for generated molecules.

    GPU Support
    ~~~~~~~~~~~
    - useGpu:
        Execute FLOWR using GPU acceleration.

    - gpuList:
        GPU devices available for execution.

    Output
    ------
    - outputSmallMolecules:
        SetOfSmallMolecules containing all generated ligands.

    Each generated molecule includes:
        - Molecular structure (SDF format)
        - Automatically assigned molecule identifier
        - Preserved portions of the original ligand
        - Regenerated molecular region
        - Optional affinity predictions (if requested)

    Use Cases
    ---------
    - Lead optimization
    - Local modification of known binders
    - Toxicity reduction through targeted redesign
    - Improving ADMET properties while preserving activity
    - Scaffold refinement
    - Exploration of alternative substituents
    - Protein-guided medicinal chemistry workflows
    - Structure-based molecular editing
    """
    _label = 'Molecular inpainting'

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """
        form.addHidden('useGpu', params.BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation. Choose one.")

        form.addHidden('gpuList', params.StringParam, default='0',
                       label="Choose GPU IDs",
                       help="Comma-separated GPU devices that can be used.")


        form.addSection(label='Input')
        ProtDenovoGeneration.mainParams(form)

        group = form.addGroup('Parameters')
        group.addParam('atoms', params.StringParam, default='',
                       label='Atoms to modify: ',
                       help=(
                           "Specify atom indices to modify.\n"
                           "You can provide individual atoms separated by commas (e.g. 13,14,15),\n"
                           "or use ranges with a hyphen (e.g. 13-18, which expands to 13,14,15,16,17,18).\n"
                           "Both formats can be combined (e.g. 1-3,7,10-12)."
                       ))

        ProtDenovoGeneration.parameters(group)

        group.addParam('filterCondSubstructure', params.BooleanParam,
                       default=False,
                       label="Strict substructure filtering: ",
                       help="If enabled, generated molecules that do not contain the specified substructure will be discarded. This may fail if invalid molecules are produced during generation.")

        form.addParallelSection(threads=4, mpi=1)

    # --------------------------- STEPS functions ------------------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.convertFilesStep)
        self._insertFunctionStep(self.createLigandFileStep)
        self._insertFunctionStep(self.runFlowrStep)
        self._insertFunctionStep(self.genIndivMoleculesStep)

        self._insertFunctionStep(self.createOutputStep)

    def convertFilesStep(self):
        return utils._convertFiles(self)

    def createLigandFileStep(self):
        utils._createLigandFile(self)

    def runFlowrStep(self):
        scriptPath = os.path.join(Plugin.getVar(FLOWR_DIC['home']),'flowr_root/flowr/gen/generate_from_pdb.py')
        outPath = self._getExtraPath('inpainting')

        struct = self.inputAtomStruct.get()
        fileName = struct.getFileName()
        base = os.path.splitext(os.path.basename(fileName))[0]
        outFile = self._getExtraPath(base + '.pdb')
        if not os.path.exists(outFile):
            outFile = os.path.abspath(self.inputAtomStruct.get().getFileName())

        args = utils._createArgs(self, outFile, outPath)

        if self.filterCondSubstructure.get():
            args.append('--filter_cond_substructure')

        args.append('--substructure_inpainting')
        args.append('--substructure')
        args = args+(self.parse_atoms(self.atoms.get()))

        fullProgram = (
            f"export PYTHONPATH={os.path.join(Plugin.getVar(FLOWR_DIC['home']),'flowr_root')}:$PYTHONPATH && "
            f"python"
        )

        args_str = " ".join(map(str, args))

        Plugin.runCondaCommand(
            self,
            program=fullProgram,
            args=f"{scriptPath} {args_str}",
            condaDic=FLOWR_DIC,
            cwd=Plugin.getVar(self._getExtraPath())
        )

    def genIndivMoleculesStep(self):
        utils._individualMols(self, 'inpainting')

    def createOutputStep(self):
        sdfs = glob.glob(os.path.join(self._getPath(), '*.sdf'))
        outMols = SetOfSmallMolecules().create(outputPath=self._getPath())
        outMols.setProteinFile(self.inputAtomStruct.get().getFileName())
        for sdf in sdfs:
            molName = os.path.splitext(os.path.basename(sdf))[0]
            mol = SmallMolecule(smallMolFilename=sdf, molName=molName)

            if self.affinity.get():
                props = utils._extractSdfProperties(sdf)
                mol.pIC50 = Float()
                mol.pKi = Float()
                mol.pKd = Float()
                mol.pEC50 = Float()
                mol.setAttributeValue('pIC50', props.get("pic50"))
                mol.setAttributeValue('pKi', props.get("pki"))
                mol.setAttributeValue('pKd', props.get("pkd"))
                mol.setAttributeValue('pEC50', props.get("pec50"))

            outMols.append(mol)

        self._defineOutputs(outputSmallMolecules=outMols)

    # --------------------------- INFO functions -----------------------------------
    def _summary(self):
        summary = []
        return summary

    def _methods(self):
        methods = []
        return methods

    def _validate(self):
        validations = []
        return validations

    def _warnings(self):
        warnings = []
        return warnings

    # --------------------------- UTILS functions -----------------------------------

    def parse_atoms(self, atom_str):
        atoms = []

        for part in re.split(r'[\s,]+', atom_str.strip()):
            if not part:
                continue

            if '-' in part:
                start, end = map(int, part.split('-'))
                atoms.extend(range(start - 1, end))
            else:
                atoms.append(int(part) - 1)

        return atoms